/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "facebooktest_constants.h"

namespace facebook { namespace fb303 {

const facebooktestConstants g_facebooktest_constants;

facebooktestConstants::facebooktestConstants() {
}

}} // namespace

