/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef facebooktest_CONSTANTS_H
#define facebooktest_CONSTANTS_H

#include "facebooktest_types.h"

namespace facebook { namespace fb303 {

class facebooktestConstants {
 public:
  facebooktestConstants();

};

extern const facebooktestConstants g_facebooktest_constants;

}} // namespace

#endif
